Corrected compile errors
ApryseSDK/webviewer-jquery-sample pull request #2
Opened 2024-09-03 15:38 UTC by Mohammed-AbdulRahman-Apryse

1. Updated the UI to the variable.
2. Updated the jQuery.
3. Updated the contact sales statement.
4. Added the automatically loading of localhost.
5. Updated the dependencies versions.
6. Updated readme contents, links and structure.

2024-09-09 18:47 UTC, mparizeau-pdftron requested changes

2024-09-09 18:47 UTC, mparizeau-pdftron commented on LICENSE
>  Copyright 2018 PDFTron Systems Inc. All rights reserved.
Can we make this license 2024 Apryse? For example https://github.com/ApryseSDK/webviewer-ui/blob/10.12/LICENSE

2024-09-09 18:47 UTC, mparizeau-pdftron commented on README.md
> +It will load `http://localhost:3000/`. The application will automatically reload when possible changes occurred to the source files.
```suggestion
It will load `http://localhost:3000/`. The application will automatically reload if you change any of the source files.
```
I think I like the original phrasing better here

2024-09-09 18:47 UTC, mparizeau-pdftron commented on eslint.config.mjs
> +import js from '@eslint/js';
Just wondering why we added eslint to this repo? Was it on purpose? It wasn't mentioned in the PR description and doesn't really seem necessary for a sample.

2024-09-19 07:55 UTC, Mohammed-AbdulRahman-Apryse commented
>>> In LICENSE<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750752671>:
>>> Can we make this license 2024 Apryse? For example https://github.com/ApryseSDK/webviewer-ui/blob/10.12/LICENSE

Yes, I changed it to 2024.

----------------------------------------------------
>>> In README.md<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750753683>:
>>> I think I like the original phrasing better here
>>> It will load `http://localhost:3000/`. The application will automatically reload if you change any of the source files.

I changed it in the source.

----------------------------------------------------
>>> In eslint.config.mjs<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750755194>:
>>> +import js from ***@***.***/js';
>>> Just wondering why we added eslint to this repo? Was it on purpose? It wasn't mentioned in the PR description and doesn't really seem necessary for a sample.

The CONTRIBUTING.md<https://github.com/ApryseSDK/webviewer-jquery-sample/blob/master/CONTRIBUTING.md> -> Pull requests -> step# 4 is stating: Lint your code with `npm run lint`.
I hope this describes the addition of eslint.

So do think I should remove it from the project, and remove the step# 4 of CONTRIBUTING.md?


________________________________
From: Matt Parizeau ***@***.***>
Sent: Monday, September 9, 2024 9:47 PM
To: ApryseSDK/webviewer-jquery-sample ***@***.***>
Cc: Mohammed AbdulRahman ***@***.***>; Author ***@***.***>
Subject: Re: [ApryseSDK/webviewer-jquery-sample] Corrected compile errors (PR #2)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@mparizeau-pdftron requested changes on this pull request.

________________________________

In LICENSE<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750752671>:

> @@ -1,2 +1,2 @@
 Copyright 2018 PDFTron Systems Inc. All rights reserved.


Can we make this license 2024 Apryse? For example https://github.com/ApryseSDK/webviewer-ui/blob/10.12/LICENSE

________________________________

In README.md<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750753683>:

> @@ -24,15 +24,11 @@ npm install
 npm start
 ```

-Navigate to `http://localhost:3000/`. The app will automatically reload if you change any of the source files.
+It will load `http://localhost:3000/`. The application will automatically reload when possible changes occurred to the source files.


⬇️ Suggested change

-It will load `http://localhost:3000/`. The application will automatically reload when possible changes occurred to the source files.
+It will load `http://localhost:3000/`. The application will automatically reload if you change any of the source files.


I think I like the original phrasing better here

________________________________

In eslint.config.mjs<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#discussion_r1750755194>:

> @@ -0,0 +1,77 @@
+import js from ***@***.***/js';


Just wondering why we added eslint to this repo? Was it on purpose? It wasn't mentioned in the PR description and doesn't really seem necessary for a sample.

—
Reply to this email directly, view it on GitHub<https://github.com/ApryseSDK/webviewer-jquery-sample/pull/2#pullrequestreview-2290685317>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BK57WX7TU4GJBG5ZIJYYLPLZVXUM5AVCNFSM6AAAAABNSNIRM6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOJQGY4DKMZRG4>.
You are receiving this because you authored the thread.

2024-09-20 19:39 UTC, mparizeau-pdftron requested changes
Since lint is already done now it's fine we can just keep it. 

For the other changes it doesn't look like they got pushed through to the PR.

2024-10-10 18:00 UTC, mparizeau-pdftron requested changes

2024-10-10 18:00 UTC, mparizeau-pdftron commented on LICENSE
> +Copyright 2024 PDFTron Systems Inc. All rights reserved.
Can we change this to Apryse

2024-11-06 01:18 UTC, merged